### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by classPythonAddike** [SnowballSH/HumanScript#1]
@SnowballSH , (btw this is a gr8 project) why don't you try adding features that other languages have, like compiling it into executables, adding 'HumanScript' to PATH, so I can run files from the command line, etc. etc.? This could actually become a popular language with the r8 features!

**Comment by SnowballSH** [comment]
Thanks for reaching out, these are my answers:
1. I do not plan to build the language to compiling code into executable. First, I don't want to use LLVM, because it does not work on my pc. Second, If I make it into a compiled language, it would be a lot harder to code in (must be statically typed)
2. It is planned, however, to build the whole project into executable. If you want to run it now, there is a [repl](https://repl.it/@SnowballSH/HumanScript) for this language. Just simply click "run".
If any other questions feel free to ask more :>

**Comment by SnowballSH** [comment]
lmao
